// @ts-check
import { defineConfig } from 'astro/config';
import { readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import AutoImport from 'unplugin-auto-import/astro';

const componentsDirectory = fileURLToPath(new URL('./src/components/', import.meta.url));
const componentNames = new Set();
// Astro's default exports are generated by its compiler, so register files directly.
const componentImports = readdirSync(componentsDirectory, { recursive: true, encoding: 'utf8' })
	.filter((file) => file.endsWith('.astro'))
	.sort()
	.map((file) => {
		// fr/slide.contact.astro → FrSlideContact
		const pascalName = file.slice(0, -'.astro'.length)
			.split(/[/\\.\s_-]+/)
			.filter(Boolean)
			.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
			.join('');
		// A JavaScript identifier cannot start with a digit (1.slide.astro → _1Slide).
		const name = /^\d/.test(pascalName) ? `_${pascalName}` : pascalName;
		if (componentNames.has(name)) {
			throw new Error(`Duplicate Astro auto-import name "${name}" (${file})`);
		}
		componentNames.add(name);
		return { from: resolve(componentsDirectory, file), imports: [/** @type {[string, string]} */ (['default', name])] };
	});

const [owner = '', repository = ''] = (process.env.GITHUB_REPOSITORY ?? '').split('/');
const isGitHubPages = process.env.DEPLOY_TARGET === 'github-pages' && Boolean(owner && repository);
const isUserSite = repository === `${owner}.github.io`;

// https://astro.build/config
export default defineConfig({
	site: isGitHubPages ? `https://${owner}.github.io` : process.env.SITE_URL || undefined,
	base: isGitHubPages ? (isUserSite ? '/' : `/${repository}`) : process.env.BASE_PATH || '/',
	i18n: {
    	locales: ["en", "fr", "nl"],
    	defaultLocale: "fr",
  	},
	integrations: [
		AutoImport({
			imports: componentImports,
			dts: './.astro/auto-imports.d.ts',
			dtsMode: 'overwrite',
		}),
	],
});
